//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patient_Portal.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Patient_Portal.Shared.ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MSGBOX_Cancel {
            get {
                return ResourceManager.GetString("MSGBOX_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MSGBOX_No {
            get {
                return ResourceManager.GetString("MSGBOX_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string MSGBOX_OK {
            get {
                return ResourceManager.GetString("MSGBOX_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MSGBOX_Yes {
            get {
                return ResourceManager.GetString("MSGBOX_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Appointment.
        /// </summary>
        public static string NAV_MENU_NEW_APT {
            get {
                return ResourceManager.GetString("NAV_MENU_NEW_APT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Allergies.
        /// </summary>
        public static string NAV_MENU_SHOW_ALLERGIES {
            get {
                return ResourceManager.GetString("NAV_MENU_SHOW_ALLERGIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Appointments.
        /// </summary>
        public static string NAV_MENU_SHOW_APT {
            get {
                return ResourceManager.GetString("NAV_MENU_SHOW_APT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Documents.
        /// </summary>
        public static string NAV_MENU_SHOW_DOCS {
            get {
                return ResourceManager.GetString("NAV_MENU_SHOW_DOCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string NAV_MENU_SHOW_LOGOUT {
            get {
                return ResourceManager.GetString("NAV_MENU_SHOW_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Portal.
        /// </summary>
        public static string NAV_MENU_Title {
            get {
                return ResourceManager.GetString("NAV_MENU_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string PAGE_ALLERGY_Code {
            get {
                return ResourceManager.GetString("PAGE_ALLERGY_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PAGE_ALLERGY_Name {
            get {
                return ResourceManager.GetString("PAGE_ALLERGY_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string PAGE_APPOINTMENT_Date {
            get {
                return ResourceManager.GetString("PAGE_APPOINTMENT_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        public static string PAGE_APPOINTMENT_Resource {
            get {
                return ResourceManager.GetString("PAGE_APPOINTMENT_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PAGE_APPOINTMENT_Status {
            get {
                return ResourceManager.GetString("PAGE_APPOINTMENT_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string PAGE_AUTH_BTN_Authenticate {
            get {
                return ResourceManager.GetString("PAGE_AUTH_BTN_Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Appointment without Login.
        /// </summary>
        public static string PAGE_AUTH_BTN_SendDirect {
            get {
                return ResourceManager.GetString("PAGE_AUTH_BTN_SendDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the terms and conditions of SENA SDN. BHD..
        /// </summary>
        public static string PAGE_AUTH_CONF_AGREE {
            get {
                return ResourceManager.GetString("PAGE_AUTH_CONF_AGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PAGE_AUTH_CONF_Cancel {
            get {
                return ResourceManager.GetString("PAGE_AUTH_CONF_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation code was sent to the following Phone Number:.
        /// </summary>
        public static string PAGE_AUTH_CONF_DESCR {
            get {
                return ResourceManager.GetString("PAGE_AUTH_CONF_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string PAGE_AUTH_CONF_OK {
            get {
                return ResourceManager.GetString("PAGE_AUTH_CONF_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter confirmation code.
        /// </summary>
        public static string PAGE_AUTH_CONF_PLACEHOLDER {
            get {
                return ResourceManager.GetString("PAGE_AUTH_CONF_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string PAGE_AUTH_DOB {
            get {
                return ResourceManager.GetString("PAGE_AUTH_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string PAGE_AUTH_Email {
            get {
                return ResourceManager.GetString("PAGE_AUTH_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NRIC / Passport.
        /// </summary>
        public static string PAGE_AUTH_ID {
            get {
                return ResourceManager.GetString("PAGE_AUTH_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE LA LOGIN.
        /// </summary>
        public static string PAGE_AUTH_TITLE_AUTH {
            get {
                return ResourceManager.GetString("PAGE_AUTH_TITLE_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Confirmation Code.
        /// </summary>
        public static string PAGE_AUTH_TITLE_CONF {
            get {
                return ResourceManager.GetString("PAGE_AUTH_TITLE_CONF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the disclaimer to continue!.
        /// </summary>
        public static string PAGE_AUTH_VAL_Disclaimer {
            get {
                return ResourceManager.GetString("PAGE_AUTH_VAL_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the confirmation code!.
        /// </summary>
        public static string PAGE_AUTH_VAL_NoConfCode {
            get {
                return ResourceManager.GetString("PAGE_AUTH_VAL_NoConfCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string PAGE_DOC_Date {
            get {
                return ResourceManager.GetString("PAGE_DOC_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing request was sent..
        /// </summary>
        public static string PAGE_DOC_MailSent {
            get {
                return ResourceManager.GetString("PAGE_DOC_MailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open document.
        /// </summary>
        public static string PAGE_DOC_OpenLink {
            get {
                return ResourceManager.GetString("PAGE_DOC_OpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string PAGE_DOC_Title {
            get {
                return ResourceManager.GetString("PAGE_DOC_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string PAGE_DOC_Type {
            get {
                return ResourceManager.GetString("PAGE_DOC_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string PAGE_DOC_View {
            get {
                return ResourceManager.GetString("PAGE_DOC_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging out....
        /// </summary>
        public static string PAGE_LOGOUT_Title {
            get {
                return ResourceManager.GetString("PAGE_LOGOUT_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the menu for navigation.
        /// </summary>
        public static string PAGE_NAV_Info {
            get {
                return ResourceManager.GetString("PAGE_NAV_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not logged in. Redirecting to login page in 5 seconds....
        /// </summary>
        public static string PAGE_NAV_NotLoggedIn {
            get {
                return ResourceManager.GetString("PAGE_NAV_NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome,.
        /// </summary>
        public static string PAGE_NAV_Welcome {
            get {
                return ResourceManager.GetString("PAGE_NAV_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PAGE_NEWAPT_Cancel {
            get {
                return ResourceManager.GetString("PAGE_NEWAPT_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string PAGE_NEWAPT_DOB {
            get {
                return ResourceManager.GetString("PAGE_NEWAPT_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        public static string PAGE_NEWAPT_DT {
            get {
                return ResourceManager.GetString("PAGE_NEWAPT_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string PAGE_NEWAPT_Email {
            get {
                return ResourceManager.GetString("PAGE_NEWAPT_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string PAGE_NEWAPT_PatId {
            get {
                return ResourceManager.GetString("PAGE_NEWAPT_PatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PAGE_NEWAPT_PatName {
            get {
                return ResourceManager.GetString("PAGE_NEWAPT_PatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PAGE_NEWAPT_Phone {
            get {
                return ResourceManager.GetString("PAGE_NEWAPT_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        public static string PAGE_NEWAPT_Resource {
            get {
                return ResourceManager.GetString("PAGE_NEWAPT_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string PAGE_NEWAPT_Send {
            get {
                return ResourceManager.GetString("PAGE_NEWAPT_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string PAGE_NEWAPT_ServiceSelection {
            get {
                return ResourceManager.GetString("PAGE_NEWAPT_ServiceSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment request successfully sent..
        /// </summary>
        public static string PAGE_NEWAPT_Success {
            get {
                return ResourceManager.GetString("PAGE_NEWAPT_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptoms.
        /// </summary>
        public static string PAGE_NEWAPT_Symptoms {
            get {
                return ResourceManager.GetString("PAGE_NEWAPT_Symptoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Request.
        /// </summary>
        public static string PAGE_NEWAPT_Title {
            get {
                return ResourceManager.GetString("PAGE_NEWAPT_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address!.
        /// </summary>
        public static string PAGE_NEWAPT_VAL_Email {
            get {
                return ResourceManager.GetString("PAGE_NEWAPT_VAL_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your ID number!.
        /// </summary>
        public static string PAGE_NEWAPT_VAL_Id {
            get {
                return ResourceManager.GetString("PAGE_NEWAPT_VAL_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name!.
        /// </summary>
        public static string PAGE_NEWAPT_VAL_Name {
            get {
                return ResourceManager.GetString("PAGE_NEWAPT_VAL_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your phone number!.
        /// </summary>
        public static string PAGE_NEWAPT_VAL_Phone {
            get {
                return ResourceManager.GetString("PAGE_NEWAPT_VAL_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a resource!.
        /// </summary>
        public static string PAGE_NEWAPT_VAL_Resource {
            get {
                return ResourceManager.GetString("PAGE_NEWAPT_VAL_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your symptoms!.
        /// </summary>
        public static string PAGE_NEWAPT_VAL_Symptoms {
            get {
                return ResourceManager.GetString("PAGE_NEWAPT_VAL_Symptoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string WS_ERROR {
            get {
                return ResourceManager.GetString("WS_ERROR", resourceCulture);
            }
        }
    }
}
